# DPS provisioning with symmetric key
[DeviceProvisioning]
Method = "symmetric_key"
IdScope = "0cn0030BD6256B6"
OrderId = "ce19024381-3d234wef-4d0jc234-94h24e-ba7g42dfb6c4a161d"
PolicyName = "registration"
DevEndPoint = "global.azure-devices-provisioning.cn"
RegBaseUrl = "%s/%s/registrations/%s/register?api-version=2021-06-01"
RegStatusBaseUrl = "%s/%s/registrations/%s?api-version=2021-06-01"

[CommonKeys]
PrimaryKey = "3k/K7JPeXrG+abUKsdglDkJbB56qaB1D1PO74G/AqY4da56C2hXMvdAl1nW2sfYfr7UGNvba562HRNhlUi9egqUbj6Hgbc1dg=="
SecondaryKey = "SU3hAUJtn5chjaz/DsdfHhyChbIUKdQq54nEFBPwEz5bg9sgm8byA56BzTso0sfGaKeLasJEBnRe1KnInYrooCgfkGKxg=="
RegistrationId = "202200000device626" #设备mac

[DataUploadConf]
IdentityId = "0a5270865c5gdfdb1d56eqw8b7a76cdfg51370520f85601"
Pid = "010000000000000000000000001ecddadfdgc0001"
MsgType = "dataUpload"
FirmwareVersion = "1.0"
TimeVal = 300 # 周期上报数据 默认300秒(1分钟)

[DirectMethodConf]
MethodName = "TestMethod" # 调用方法名称
SuccessStatusCode = 200 # 调用方法名称返回code
MethodJsonPath = "method.json" # # 调用方法返回参数配置文件
